# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath C:/modeltech64_10.4/win64
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z045ffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/TEST/Graduation_Rectify/Axi_FIFO/project_1/project_1.cache/wt [current_project]
set_property parent.project_path F:/TEST/Graduation_Rectify/Axi_FIFO/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc706:part0:1.3 [current_project]
set_property ip_output_repo f:/TEST/Graduation_Rectify/Axi_FIFO/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib F:/TEST/Graduation_Rectify/Axi_FIFO/project_1/project_1.srcs/sources_1/new/ff.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top ff -part xc7z045ffg900-2


write_checkpoint -force -noxdef ff.dcp

catch { report_utilization -file ff_utilization_synth.rpt -pb ff_utilization_synth.pb }
